version: "3.9"

services:
  bot:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db

  bot-dev:
    build: .
    command: watchfiles --filter python "python -m bot.main"
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-botdb}
      POSTGRES_USER: ${DB_USER:-bot}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-botpass}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
