"""Initial migration with all tables

Revision ID: cff4899c4c1c
Revises: 
Create Date: 2025-07-12 18:28:15.610753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff4899c4c1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('spam_limit', sa.Integer(), nullable=False),
    sa.Column('spam_interval', sa.Integer(), nullable=False),
    sa.Column('repeat_limit', sa.Integer(), nullable=False),
    sa.Column('repeat_interval', sa.Integer(), nullable=False),
    sa.Column('link_spam_limit', sa.Integer(), nullable=False),
    sa.Column('link_spam_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_settings_chat_id'), 'group_settings', ['chat_id'], unique=True)
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(length=255), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('response_file_id', sa.String(length=255), nullable=True),
    sa.Column('response_file_type', sa.String(length=20), nullable=True),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('is_pattern', sa.Boolean(), nullable=False),
    sa.Column('case_sensitive', sa.Boolean(), nullable=False),
    sa.Column('transliterate_enabled', sa.Boolean(), nullable=False),
    sa.Column('fuzzy_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_phrase'), 'keywords', ['phrase'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keywords_phrase'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_group_settings_chat_id'), table_name='group_settings')
    op.drop_table('group_settings')
    # ### end Alembic commands ###
